# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WFNetworkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WFNetworkingDemo
  pod 'AFNetworking'

  target 'WFNetworkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WFNetworkingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
